MULE-18677: add architecture discovery logic

diff --git a/standalone/src/main/resources/bin/mule b/standalone/src/main/resources/bin/mule
--- a/standalone/src/main/resources/bin/mule
+++ b/standalone/src/main/resources/bin/mule
@@ -194,8 +194,20 @@ then
 fi
 PSKEYWORD="args"
 
+TR_BIN="/usr/bin/tr"
+if [ ! -x "$TR_BIN" ]
+then
+    TR_BIN="/bin/tr"
+    if [ ! -x "$TR_BIN" ]
+    then
+        eval echo `gettext 'Unable to locate "tr".'`
+        eval echo `gettext 'Please report this message along with the location of the command on your system.'`
+        exit 1
+    fi
+fi
+
 # Resolve the os
-DIST_OS=`uname -s | tr [:upper:] [:lower:] | tr -d [:blank:]`
+DIST_OS=`uname -s | $TR_BIN [:upper:] [:lower:] | $TR_BIN -d [:blank:]`
 case "$DIST_OS" in
     'sunos')
         DIST_OS="solaris"
@@ -219,57 +231,165 @@ esac
 # Patched for Mule (MULE-1288, MULE-1322, MULE-1337, MULE-1396)
 ######################################################################
 
+# Compare Versions $1<$2=0, $1==$2=1, $1>$2=2
+compareVersions () {
+    if [ "$1" = "$2" ]
+    then
+        return 1
+    else
+        local i=1
+        while true
+        do
+            local v1=`echo "$1" | cut -d '.' -f $i`
+            local v2=`echo "$2" | cut -d '.' -f $i`
+            if [ "X$v1" = "X" ]
+            then
+                if [ "X$v2" = "X" ]
+                then
+                    return 1
+                fi
+                v1="0"
+            elif [ "X$v2" = "X" ]
+            then
+                v2="0"
+            fi
+            if [ $v1 -lt $v2 ]
+            then
+                return 0
+            elif [ $v1 -gt $v2 ]
+            then
+                return 2
+            fi
+            i=`expr $i + 1`
+        done
+    fi
+}
+
 # Resolve the architecture
-UNAME_PROC_OPTION="-m"
-if [ "$DIST_OS" = "aix" ]; then
-    UNAME_PROC_OPTION="-p"
-fi
-
-PROC_ARCH=`uname $UNAME_PROC_OPTION | tr [:upper:] [:lower:] | tr -d [:blank:]`
-
-# The previous approach was this:
-# If a 32-bit wrapper binary exists then it will work on 32 or 64 bit
-# platforms, if the 64-bit binary exists then the distribution most
-# likely wants to use long names.
-DIST_BITS="32"
-
-while :
-do
-    case "$PROC_ARCH" in
-        'amd64' | 'athlon' | 'i386' | 'i486' | 'i586' | 'i686' | 'i86pc')
-            DIST_ARCH="x86"
-            break;;
-        'x86_64')
-            DIST_ARCH="x86"
-            # on 64 bit Linuxes the 32 bit subsystem may not be installed so
-            # let's use the 64 bit wrapper
+if [ "$DIST_OS" = "macosx" ]
+then
+    OS_VER=`sw_vers | grep 'ProductVersion:' | grep -o '[0-9]*\.[0-9]*\.[0-9]*\|[0-9]*\.[0-9]*'`
+    DIST_ARCH="universal"
+    compareVersions "$OS_VER" "10.5.0"
+    if [ $? -lt 1 ]
+    then
+        DIST_BITS="32"
+    else
+        if [ "X`/usr/sbin/sysctl -n hw.cpu64bit_capable`" = "X1" ]  
+        then
             DIST_BITS="64"
-            break;;
-        'ia32' | 'ia64')
-             DIST_ARCH="ia"
-            break;;
+        else
+            DIST_BITS="32"
+        fi
+    fi
+elif [ "$DIST_OS" = "zos" ] ; then
+    # Z/Os is not supported in the Delta Pack, therefore we only provide a binary
+    # file named "wrapper". However this script will still check for a file named
+    # "wrapper-zos-390-32" and "wrapper-zos-390-64" in case the user edited the name.
+    DIST_ARCH="390"
+    DIST_BITS="64"
+else
+    if [ "$DIST_OS" = "linux" ]
+    then
+        DIST_ARCH=
+    else
+        DIST_ARCH=`uname -p 2>/dev/null | $TR_BIN "[A-Z]" "[a-z]" | $TR_BIN -d ' '`
+    fi
+    if [ "X$DIST_ARCH" = "X" ]
+    then
+        DIST_ARCH="unknown"
+    fi
+    if [ "$DIST_ARCH" = "unknown" ]
+    then
+        DIST_ARCH=`uname -m 2>/dev/null | $TR_BIN "[A-Z]" "[a-z]" | $TR_BIN -d ' '`
+    fi
+    case "$DIST_ARCH" in
+        'athlon' | 'i386' | 'i486' | 'i586' | 'i686')
+            DIST_ARCH="x86"
+            if [ "${DIST_OS}" = "solaris" ] ; then
+                DIST_BITS=`isainfo -b`
+            else
+                DIST_BITS="32"
+            fi
+            ;;
+        'amd64' | 'x86_64')
+            DIST_ARCH="x86"
+            DIST_BITS="64"
+            ;;
+        'ia32')
+            DIST_ARCH="ia"
+            DIST_BITS="32"
+            ;;
+        'ia64' | 'ia64n' | 'ia64w')
+            DIST_ARCH="ia"
+            DIST_BITS="64"
+            ;;
         'ip27')
             DIST_ARCH="mips"
-            break;;
-        'power' | 'powerpc' | 'power_pc' | 'ppc64' | 'powermacintosh')
-            DIST_ARCH="ppc"
-            break;;
+            DIST_BITS="32"
+            ;;
+        'ppc64le')
+            DIST_ARCH="ppcle"
+            DIST_BITS="64"
+            ;;
+        'power' | 'powerpc' | 'power_pc' | 'ppc64')
+            if [ "${DIST_ARCH}" = "ppc64" ] ; then
+                DIST_BITS="64"
+            else
+                DIST_BITS="32"
+            fi
+            DIST_ARCH="ppcbe"
+            
+            if [ "${DIST_OS}" = "aix" ] ; then
+                DIST_ARCH="ppc"
+                if [ `getconf KERNEL_BITMODE` -eq 64 ]; then
+                    DIST_BITS="64"
+                else
+                    DIST_BITS="32"
+                fi
+            fi
+            ;;
         'pa_risc' | 'pa-risc')
             DIST_ARCH="parisc"
-            break;;
-        'sun4u' | 'sun4us' | 'sun4v' | 'sparcv9' | 'sparc')
+            if [ `getconf KERNEL_BITS` -eq 64 ]; then
+                DIST_BITS="64"
+            else
+                DIST_BITS="32"
+            fi    
+            ;;
+        'sun4u' | 'sparcv9' | 'sparc')
             DIST_ARCH="sparc"
-            break;;
-        '9000/800')
+            DIST_BITS=`isainfo -b`
+            ;;
+        '9000/800' | '9000/785')
             DIST_ARCH="parisc"
-            break;;
-        *)
-            echo "Your machine's hardware type (uname $UNAME_PROC_OPTION) was not recognized by the Service Wrapper as a supported platform."
-            echo "Please report this message along with your machine's processor/architecture."
-            exit 1
+            if [ `getconf KERNEL_BITS` -eq 64 ]; then
+                DIST_BITS="64"
+            else
+                DIST_BITS="32"
+            fi
+            ;;
+        s390* )
+            DIST_ARCH="390"
+            if [ `getconf LONG_BIT` -eq 64 ] ; then
+                DIST_BITS="64"
+            else
+                DIST_BITS="32"
+            fi
+            ;;
+        armv*)
+            if [ -z "`readelf -A /proc/self/exe | grep Tag_ABI_VFP_args`" ] ; then 
+                DIST_ARCH="armel"
+                DIST_BITS="32"
+            else 
+                DIST_ARCH="armhf"
+                DIST_BITS="32"
+            fi
             ;;
     esac
-done
+fi
+
+
 ######################################################################
 
 outputFile() {
@@ -281,52 +401,48 @@ outputFile() {
     fi
 }
 
-WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-$DIST_BITS"
-if [ -x "$WRAPPER_TEST_CMD" ]
-then
-    WRAPPER_CMD="$WRAPPER_TEST_CMD"
-else
-    if [ "$DIST_OS" = "macosx" ]
-    then
-        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-64"
-        if [ -x "$WRAPPER_TEST_CMD" ]
-        then
+# Check if the first parameter is an existing executable file.
+detectWrapperBinary() {
+    if [ -f "$1" ] ; then
+        WRAPPER_TEST_CMD="$1"
+        if [ ! -x "$WRAPPER_TEST_CMD" ] ; then
+            chmod +x "$WRAPPER_TEST_CMD" 2>/dev/null
+        fi
+        if [ -x "$WRAPPER_TEST_CMD" ] ; then
             WRAPPER_CMD="$WRAPPER_TEST_CMD"
         else
-            WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-            if [ -x "$WRAPPER_TEST_CMD" ]
-            then
-                WRAPPER_CMD="$WRAPPER_TEST_CMD"
-            else
-                WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-64"
-                if [ -x "$WRAPPER_TEST_CMD" ]
-                then
-                    WRAPPER_CMD="$WRAPPER_TEST_CMD"
-                else
-                    if [ ! -x "$WRAPPER_CMD" ]
-                    then
-                        echo "Unable to locate any of the following binaries:"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-universal-32"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-universal-64"
-                        outputFile "$WRAPPER_CMD"
-                        exit 1
-                    fi
-                fi
-            fi
-        fi
-    else
-        if [ ! -x "$WRAPPER_CMD" ]
-        then
-            echo "Unable to locate any of the following binaries:"
-            outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-            outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-            outputFile "$WRAPPER_CMD"
-            exit 1
+            outputFile "$WRAPPER_TEST_CMD"
+            WRAPPER_TEST_CMD=""
         fi
     fi
+}
+
+# Decide on the wrapper binary to use.
+# If the bits of the OS could be detected, we will try to look for the
+#  binary with the correct bits value.  If it doesn't exist, fall back
+#  and look for the 32-bit binary.  If that doesn't exist either then
+#  look for the default.
+WRAPPER_TEST_CMD=""
+detectWrapperBinary "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-$DIST_BITS"
+if [ -z "$WRAPPER_TEST_CMD" ] ; then
+    detectWrapperBinary "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
 fi
+if [ -z "$WRAPPER_TEST_CMD" ] ; then
+    detectWrapperBinary "$WRAPPER_CMD"
+fi
+    
+
+if [ -z "$WRAPPER_TEST_CMD" ] ; then
+    eval echo `gettext 'Unable to locate any of the following binaries:'`
+    outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-$DIST_BITS"
+    if [ ! "$DIST_BITS" = "32" ] ; then
+        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+    fi
+    outputFile "$WRAPPER_CMD"
+
+    exit 1
+fi
+
 
 # Build the nice clause
 if [ "X$PRIORITY" = "X" ]
